### ISSUE TITLE
Information collides with FPS indicator

### ISSUE THREAD

**Issue by Ivor808** [Tatters654/tick-tracker#3]
![image](https://user-images.githubusercontent.com/8969211/171297819-62074fca-3ae4-427b-98a5-9273ec321ec7.png)

**Comment by zombiezrule** [comment]
Hi this issue is still occurring
https://i.imgur.com/UQDdjYW.png

**Comment by Tatters654** [comment]
@zombiezrule Increase height offset in the config panel to fix this
