### ISSUE TITLE
Suggestion: "Crowdsource" world stability

### ISSUE THREAD

**Issue by null-zero** [Tatters654/tick-tracker#4]
I realize this hasn't been updated in a while, but it would be cool to add a crowdsource feature that would collect data from all players using the plugin to report which worlds seem to be stable at the current moment

**Comment by Tatters654** [comment]
The data wouldn't be 100% true, since peoples personal ISP and network issues effect Tick Tracker. I have thought of this, but it seems very complex to do and I'm not personally interested in pursuing this functionality.

**Comment by null-zero** [comment]
It doesn't really need to be 100% true, you can ignore the top high and low extremes and then avg the rest, sure it isn't perfect for everybody but it would be useful for the avg user
