### ISSUE TITLE
Suggestion: Add 'rolling average' option to more accurately display server health

### ISSUE THREAD

**Issue by RedCondor6** [Tatters654/tick-tracker#5]
Over long login sessions the average server health value gets skewed if the server suddenly degrades in performance (or improves). If the plugin could be configured to use data points from the last 5 minutes for example, it may provide a more accurate representation of the servers actual health. 

Thanks very much for all your work on the plugin!

**Comment by Tatters654** [comment]
This would mean storing the data points of the last X many minutes and recalculating on every game tick. I don't see a way to calculate it on every gametick without iterating through the entire entire array every time. If you know how to do so, I'd be interested in hearing it.

**Comment by StephanBijzitter** [comment]
I can whip up a pull request if you'd like :-)
I'd make it optional and include a number input to specify how many ticks to "roll"

**Comment by wickz80** [comment]
+1

Would be happy to help implement

**Comment by Tatters654** [comment]
@StephanBijzitter @wickz80 sure, feel free to whip up a PR. Be aware that current plugin-hub distribution and current master dont match.

edit: Err, master and Phub might match, I guess I didn't merge linear_formula into master.

**Comment by Tatters654** [comment]
Preferably PR to Linear_formula_calculation branch.

**Comment by Toocanzs** [comment]
I threw together a pull request for this + a rolling standard deviation in #6

I don't think the rolling average is very useful as it hovers at 600ms almost always but I think the rolling standard deviation is a very good higher=worse measure of how bad a server is which might be what you were looking for

**Comment by Toocanzs** [comment]
@StephanBijzitter Pinging you to let you know in case you were still working on this. Hopefully I didn't snipe your work too hard
