### ISSUE TITLE
Rolling average

### ISSUE THREAD

**Issue by clementchen163** [Tatters654/tick-tracker#8]
is it possible to have the percentage of good ticks (as well as bad) be calculated as a rolling average so it only takes into account the last 1000 ticks (customizable). currently the tick tracker is not useful after 3 hours of playtime as any tick issues will be hidden by the data before it

**Comment by Tatters654** [comment]
Discussed also in #5 

I would like to add this, but I haven't come up with a way of calculating it without keeping track of all the tick data since login. If you do know of a way to do so, I can look into implementing it.
